webtalk_init -webtalk_dir G:/Agha_VHDL/Uebung1/halbaddierer/halbaddierer.sim/sim_1/behav/xsim/xsim.dir/Volladdierer_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Apr 24 16:07:13 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211030922_1777584471_0_129" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a4bb987b-49b0-4145-8fd2-b1eeacf1b364" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "9875ebc8f9db4757b58dba3fde8b790e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2808 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8884_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2957930082 -regid "211030922_1777584471_0_129" -xml G:/Agha_VHDL/Uebung1/halbaddierer/halbaddierer.sim/sim_1/behav/xsim/xsim.dir/Volladdierer_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html G:/Agha_VHDL/Uebung1/halbaddierer/halbaddierer.sim/sim_1/behav/xsim/xsim.dir/Volladdierer_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm G:/Agha_VHDL/Uebung1/halbaddierer/halbaddierer.sim/sim_1/behav/xsim/xsim.dir/Volladdierer_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
